<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2010

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ns0="urn:hl7-org:v3" exclude-result-prefixes="xs ns0">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<xsl:variable name="var1_instance_L32_ClinicalDocument" select="."/>
		<patient xmlns="http://projecthdata.org/hdata/schemas/2009/06/patient_information" xmlns:core="http://projecthdata.org/hdata/schemas/2009/06/core">
			<xsl:attribute name="xsi:schemaLocation" namespace="http://www.w3.org/2001/XMLSchema-instance">
				<xsl:value-of select="'http://projecthdata.org/hdata/schemas/2009/06/patient_information Z:/projects/hl7-tsc-project/hdata-schemas/patient.xsd'"/>
			</xsl:attribute>
			<core:name>
				<xsl:for-each select="$var1_instance_L32_ClinicalDocument/ns0:ClinicalDocument/ns0:recordTarget/ns0:patientRole/ns0:patient/ns0:name/ns0:prefix">
					<xsl:variable name="var2_prefix" select="."/>
					<core:title>
						<xsl:value-of select="string($var2_prefix)"/>
					</core:title>
				</xsl:for-each>
				<xsl:for-each select="$var1_instance_L32_ClinicalDocument/ns0:ClinicalDocument/ns0:recordTarget/ns0:patientRole/ns0:patient/ns0:name/ns0:given">
					<xsl:variable name="var4_given" select="."/>
					<core:given>
						<xsl:value-of select="string($var4_given)"/>
					</core:given>
				</xsl:for-each>
				<xsl:for-each select="$var1_instance_L32_ClinicalDocument/ns0:ClinicalDocument">
					<xsl:variable name="var6_ClinicalDocument" select="."/>
					<core:lastname>
						<xsl:value-of select="string($var6_ClinicalDocument/ns0:recordTarget/ns0:patientRole/ns0:patient/ns0:name/ns0:family)"/>
					</core:lastname>
				</xsl:for-each>
				<xsl:for-each select="$var1_instance_L32_ClinicalDocument/ns0:ClinicalDocument/ns0:recordTarget/ns0:patientRole/ns0:patient/ns0:name/ns0:suffix">
					<xsl:variable name="var8_suffix" select="."/>
					<core:suffix>
						<xsl:value-of select="string($var8_suffix)"/>
					</core:suffix>
				</xsl:for-each>
			</core:name>
			<core:address>
				<xsl:for-each select="$var1_instance_L32_ClinicalDocument/ns0:ClinicalDocument/ns0:recordTarget/ns0:patientRole/ns0:addr/ns0:streetAddressLine">
					<xsl:variable name="var10_streetAddressLine" select="."/>
					<core:streetAddress>
						<xsl:value-of select="string($var10_streetAddressLine)"/>
					</core:streetAddress>
				</xsl:for-each>
				<xsl:for-each select="$var1_instance_L32_ClinicalDocument/ns0:ClinicalDocument">
					<xsl:variable name="var12_ClinicalDocument" select="."/>
					<core:city>
						<xsl:value-of select="string($var12_ClinicalDocument/ns0:recordTarget/ns0:patientRole/ns0:addr/ns0:city)"/>
					</core:city>
				</xsl:for-each>
				<xsl:for-each select="$var1_instance_L32_ClinicalDocument/ns0:ClinicalDocument">
					<xsl:variable name="var14_ClinicalDocument" select="."/>
					<core:stateOrProvince>
						<xsl:value-of select="string($var14_ClinicalDocument/ns0:recordTarget/ns0:patientRole/ns0:addr/ns0:state)"/>
					</core:stateOrProvince>
				</xsl:for-each>
				<xsl:for-each select="$var1_instance_L32_ClinicalDocument/ns0:ClinicalDocument">
					<xsl:variable name="var16_ClinicalDocument" select="."/>
					<core:zip>
						<xsl:value-of select="string($var16_ClinicalDocument/ns0:recordTarget/ns0:patientRole/ns0:addr/ns0:postalCode)"/>
					</core:zip>
				</xsl:for-each>
				<xsl:for-each select="$var1_instance_L32_ClinicalDocument/ns0:ClinicalDocument/ns0:recordTarget/ns0:patientRole/ns0:addr/ns0:country">
					<xsl:variable name="var18_country" select="."/>
					<core:country>
						<xsl:value-of select="string($var18_country)"/>
					</core:country>
				</xsl:for-each>
			</core:address>
			<core:telecom>
				<xsl:for-each select="$var1_instance_L32_ClinicalDocument/ns0:ClinicalDocument/ns0:recordTarget/ns0:patientRole/ns0:telecom">
					<xsl:variable name="var20_telecom" select="."/>
					<xsl:if test="$var20_telecom/@value">
						<xsl:attribute name="value" namespace="">
							<xsl:value-of select="string($var20_telecom/@value)"/>
						</xsl:attribute>
					</xsl:if>
				</xsl:for-each>
				<xsl:for-each select="$var1_instance_L32_ClinicalDocument/ns0:ClinicalDocument/ns0:recordTarget/ns0:patientRole/ns0:telecom">
					<xsl:variable name="var22_telecom" select="."/>
					<xsl:if test="$var22_telecom/@use">
						<xsl:attribute name="use" namespace="">
							<xsl:value-of select="string($var22_telecom/@use)"/>
						</xsl:attribute>
					</xsl:if>
				</xsl:for-each>
			</core:telecom>
			<xsl:for-each select="$var1_instance_L32_ClinicalDocument/ns0:ClinicalDocument">
				<xsl:variable name="var24_ClinicalDocument" select="."/>
				<xsl:if test="$var24_ClinicalDocument/ns0:recordTarget/ns0:patientRole/ns0:id/@extension">
					<id>
						<xsl:value-of select="string($var24_ClinicalDocument/ns0:recordTarget/ns0:patientRole/ns0:id/@extension)"/>
					</id>
				</xsl:if>
			</xsl:for-each>
			<gender>
				<xsl:for-each select="$var1_instance_L32_ClinicalDocument/ns0:ClinicalDocument">
					<xsl:variable name="var26_ClinicalDocument" select="."/>
					<xsl:if test="$var26_ClinicalDocument/ns0:recordTarget/ns0:patientRole/ns0:patient/ns0:administrativeGenderCode/@code">
						<xsl:attribute name="code" namespace="">
							<xsl:value-of select="string($var26_ClinicalDocument/ns0:recordTarget/ns0:patientRole/ns0:patient/ns0:administrativeGenderCode/@code)"/>
						</xsl:attribute>
					</xsl:if>
				</xsl:for-each>
				<xsl:for-each select="$var1_instance_L32_ClinicalDocument/ns0:ClinicalDocument">
					<xsl:variable name="var28_ClinicalDocument" select="."/>
					<xsl:if test="$var28_ClinicalDocument/ns0:recordTarget/ns0:patientRole/ns0:patient/ns0:administrativeGenderCode/@codeSystem">
						<xsl:attribute name="codeSystem" namespace="">
							<xsl:value-of select="string($var28_ClinicalDocument/ns0:recordTarget/ns0:patientRole/ns0:patient/ns0:administrativeGenderCode/@codeSystem)"/>
						</xsl:attribute>
					</xsl:if>
				</xsl:for-each>
				<xsl:for-each select="$var1_instance_L32_ClinicalDocument/ns0:ClinicalDocument">
					<xsl:variable name="var30_ClinicalDocument" select="."/>
					<xsl:if test="$var30_ClinicalDocument/ns0:recordTarget/ns0:patientRole/ns0:patient/ns0:administrativeGenderCode/@codeSystemName">
						<xsl:attribute name="codeSystemName" namespace="">
							<xsl:value-of select="string($var30_ClinicalDocument/ns0:recordTarget/ns0:patientRole/ns0:patient/ns0:administrativeGenderCode/@codeSystemName)"/>
						</xsl:attribute>
					</xsl:if>
				</xsl:for-each>
				<xsl:for-each select="$var1_instance_L32_ClinicalDocument/ns0:ClinicalDocument">
					<xsl:variable name="var32_ClinicalDocument" select="."/>
					<xsl:if test="$var32_ClinicalDocument/ns0:recordTarget/ns0:patientRole/ns0:patient/ns0:administrativeGenderCode/@displayName">
						<xsl:attribute name="displayName" namespace="">
							<xsl:value-of select="string($var32_ClinicalDocument/ns0:recordTarget/ns0:patientRole/ns0:patient/ns0:administrativeGenderCode/@displayName)"/>
						</xsl:attribute>
					</xsl:if>
				</xsl:for-each>
			</gender>
			<language>
				<xsl:for-each select="$var1_instance_L32_ClinicalDocument/ns0:ClinicalDocument/ns0:recordTarget/ns0:patientRole/ns0:patient/ns0:languageCommunication">
					<xsl:variable name="var34_languageCommunication" select="."/>
					<xsl:if test="$var34_languageCommunication/ns0:languageCode/@code">
						<xsl:attribute name="code" namespace="">
							<xsl:value-of select="string($var34_languageCommunication/ns0:languageCode/@code)"/>
						</xsl:attribute>
					</xsl:if>
				</xsl:for-each>
				<xsl:for-each select="$var1_instance_L32_ClinicalDocument/ns0:ClinicalDocument/ns0:recordTarget/ns0:patientRole/ns0:patient/ns0:languageCommunication">
					<xsl:variable name="var36_languageCommunication" select="."/>
					<xsl:if test="$var36_languageCommunication/ns0:languageCode/@displayName">
						<xsl:attribute name="displayName" namespace="">
							<xsl:value-of select="string($var36_languageCommunication/ns0:languageCode/@displayName)"/>
						</xsl:attribute>
					</xsl:if>
				</xsl:for-each>
			</language>
			<xsl:for-each select="$var1_instance_L32_ClinicalDocument/ns0:ClinicalDocument">
				<xsl:variable name="var38_ClinicalDocument" select="."/>
				<xsl:if test="$var38_ClinicalDocument/ns0:recordTarget/ns0:patientRole/ns0:patient/ns0:birthTime/@value">
					<birthtime>
						<xsl:value-of select="concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(substring(string($var38_ClinicalDocument/ns0:recordTarget/ns0:patientRole/ns0:patient/ns0:birthTime/@value), 1, 4), '-'), substring(string($var38_ClinicalDocument/ns0:recordTarget/ns0:patientRole/ns0:patient/ns0:birthTime/@value), 5, 2)), '-'), substring(string($var38_ClinicalDocument/ns0:recordTarget/ns0:patientRole/ns0:patient/ns0:birthTime/@value), 7, 2)), 'T'), substring(concat(substring(string($var38_ClinicalDocument/ns0:recordTarget/ns0:patientRole/ns0:patient/ns0:birthTime/@value), 9, 2), '00'), 1, 2)), ':'), substring(concat(substring(string($var38_ClinicalDocument/ns0:recordTarget/ns0:patientRole/ns0:patient/ns0:birthTime/@value), 11, 2), '00'), 1, 2)), ':'), substring(concat(substring(string($var38_ClinicalDocument/ns0:recordTarget/ns0:patientRole/ns0:patient/ns0:birthTime/@value), 13, 2), '00'), 1, 2)), 'Z')"/>
					</birthtime>
				</xsl:if>
			</xsl:for-each>
			<maritialStatus>
				<xsl:for-each select="$var1_instance_L32_ClinicalDocument/ns0:ClinicalDocument/ns0:recordTarget/ns0:patientRole/ns0:patient/ns0:maritalStatusCode">
					<xsl:variable name="var40_maritalStatusCode" select="."/>
					<xsl:if test="$var40_maritalStatusCode/@code">
						<xsl:attribute name="code" namespace="">
							<xsl:value-of select="string($var40_maritalStatusCode/@code)"/>
						</xsl:attribute>
					</xsl:if>
				</xsl:for-each>
				<xsl:for-each select="$var1_instance_L32_ClinicalDocument/ns0:ClinicalDocument/ns0:recordTarget/ns0:patientRole/ns0:patient/ns0:maritalStatusCode">
					<xsl:variable name="var42_maritalStatusCode" select="."/>
					<xsl:if test="$var42_maritalStatusCode/@codeSystem">
						<xsl:attribute name="codeSystem" namespace="">
							<xsl:value-of select="string($var42_maritalStatusCode/@codeSystem)"/>
						</xsl:attribute>
					</xsl:if>
				</xsl:for-each>
				<xsl:for-each select="$var1_instance_L32_ClinicalDocument/ns0:ClinicalDocument/ns0:recordTarget/ns0:patientRole/ns0:patient/ns0:maritalStatusCode">
					<xsl:variable name="var44_maritalStatusCode" select="."/>
					<xsl:if test="$var44_maritalStatusCode/@codeSystemName">
						<xsl:attribute name="codeSystemName" namespace="">
							<xsl:value-of select="string($var44_maritalStatusCode/@codeSystemName)"/>
						</xsl:attribute>
					</xsl:if>
				</xsl:for-each>
				<xsl:for-each select="$var1_instance_L32_ClinicalDocument/ns0:ClinicalDocument/ns0:recordTarget/ns0:patientRole/ns0:patient/ns0:maritalStatusCode">
					<xsl:variable name="var46_maritalStatusCode" select="."/>
					<xsl:if test="$var46_maritalStatusCode/@displayName">
						<xsl:attribute name="displayName" namespace="">
							<xsl:value-of select="string($var46_maritalStatusCode/@displayName)"/>
						</xsl:attribute>
					</xsl:if>
				</xsl:for-each>
			</maritialStatus>
			<race>
				<xsl:for-each select="$var1_instance_L32_ClinicalDocument/ns0:ClinicalDocument/ns0:recordTarget/ns0:patientRole/ns0:patient/ns0:raceCode">
					<xsl:variable name="var48_raceCode" select="."/>
					<xsl:if test="$var48_raceCode/@code">
						<xsl:attribute name="code" namespace="">
							<xsl:value-of select="string($var48_raceCode/@code)"/>
						</xsl:attribute>
					</xsl:if>
				</xsl:for-each>
				<xsl:for-each select="$var1_instance_L32_ClinicalDocument/ns0:ClinicalDocument/ns0:recordTarget/ns0:patientRole/ns0:patient/ns0:raceCode">
					<xsl:variable name="var50_raceCode" select="."/>
					<xsl:if test="$var50_raceCode/@codeSystem">
						<xsl:attribute name="codeSystem" namespace="">
							<xsl:value-of select="string($var50_raceCode/@codeSystem)"/>
						</xsl:attribute>
					</xsl:if>
				</xsl:for-each>
				<xsl:for-each select="$var1_instance_L32_ClinicalDocument/ns0:ClinicalDocument/ns0:recordTarget/ns0:patientRole/ns0:patient/ns0:raceCode">
					<xsl:variable name="var52_raceCode" select="."/>
					<xsl:if test="$var52_raceCode/@codeSystemName">
						<xsl:attribute name="codeSystemName" namespace="">
							<xsl:value-of select="string($var52_raceCode/@codeSystemName)"/>
						</xsl:attribute>
					</xsl:if>
				</xsl:for-each>
				<xsl:for-each select="$var1_instance_L32_ClinicalDocument/ns0:ClinicalDocument/ns0:recordTarget/ns0:patientRole/ns0:patient/ns0:raceCode">
					<xsl:variable name="var54_raceCode" select="."/>
					<xsl:if test="$var54_raceCode/@displayName">
						<xsl:attribute name="displayName" namespace="">
							<xsl:value-of select="string($var54_raceCode/@displayName)"/>
						</xsl:attribute>
					</xsl:if>
				</xsl:for-each>
			</race>
		</patient>
	</xsl:template>
</xsl:stylesheet>
